name: Dockerize

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    uses: axieinfinity/workflows-samples/.github/workflows/docker-build.yml@main
    with:
      image_repository: us-docker.pkg.dev/axs-infra-ops-8686/skymavis/ronin-explorer-audit
    secrets: inherit
